# Generated by Django 2.2.1 on 2019-05-21 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo2Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Body')),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 21, 4, 3, 18, 294867), null=True, verbose_name='Date published')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Foo 2 item',
                'verbose_name_plural': 'Foo 2 items',
            },
        ),
        migrations.CreateModel(
            name='Foo3Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Body')),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 21, 4, 3, 18, 294867), null=True, verbose_name='Date published')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Foo 3 item',
                'verbose_name_plural': 'Foo 3 items',
            },
        ),
        migrations.CreateModel(
            name='Foo4Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Body')),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 21, 4, 3, 18, 294867), null=True, verbose_name='Date published')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Foo 4 item',
                'verbose_name_plural': 'Foo 4 items',
            },
        ),
        migrations.CreateModel(
            name='FooItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Body')),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 21, 4, 3, 18, 294867), null=True, verbose_name='Date published')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Foo item',
                'verbose_name_plural': 'Foo items',
            },
        ),
    ]
